name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * 0' # Berjalan otomatis setiap hari Minggu pukul 00:00 UTC 
  workflow_dispatch: # Memungkinkan Anda menjalankan manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          token: ${{ secrets.STAT_TOKEN }}
          path: profile/stats.svg
          options: theme=radical&show_icons=true

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          token: ${{ secrets.STAT_TOKEN }}
          path: profile/top-langs.svg
          options: theme=radical&layout=compact

      - name: Commit and Push Changes
        run: |
          git config --global user.name "NadiWarnadi"
          git config --global user.email "warnadi2006@gmail.com"
          git add profile/*.svg
          git commit -m "chore: Update GitHub Readme Stats" || exit 0
          git push
