name: Generate GitHub Summary Cards

on:
  schedule:
    - cron: '0 */12 * * *' # Berjalan setiap 12 jam otomatis
  workflow_dispatch: # Bisa dijalankan manual via tombol

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Menggunakan Action khusus pembuat kartu statistik lokal
      - uses: vn7n24f1tr1/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: NadiWarnadi
          THEME: calm

      # Menyimpan hasilnya ke folder repositori Anda otomatis
      - name: Commit & Push Gambar
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output/ || true
          git commit -m "Ubah: Perbarui gambar statistik otomatis" || true
          git push || true
